### ISSUE TITLE
[BUG] Plugin no longer seems to export GlTf for my character, only weapons

### ISSUE THREAD

**Issue by MistrxxGoat** [PassiveModding/Meddle#18]
After the update today, i noticed that when I try to export my character, I no longer get the GlTf . it simply makes a cache folder in the location I set and it is filled with the textures. 
Exporting weapons works just fine though. 
Looking at my logs, it seems I am receiving the following error

21:23:01.457 | ERR | Unobserved exception in Task.
	System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (Index was outside the bounds of the array.))
	 ---> System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
	 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
	   at Meddle.Plugin.Models.Composer.MaterialSet..ctor(MtrlFile file, String mtrlPath, ShpkFile shpk, String shpkName, HandleString[] texturePathOverride, Func`2 textureLoader) in /home/runner/work/Meddle/Meddle/Meddle/Meddle.Plugin/Models/Composer/MaterialSet.cs:line 338
	   at Meddle.Plugin.Models.Composer.CharacterComposer.<>c__DisplayClass6_0.<HandleModel>b__0(Int32 i) in /home/runner/work/Meddle/Meddle/Meddle/Meddle.Plugin/Models/Composer/CharacterComposer.cs:line 85
	   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
	--- End of stack trace from previous location ---
	   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
	   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
	   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
	--- End of stack trace from previous location ---
	   at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
	   at Meddle.Plugin.Models.Composer.CharacterComposer.HandleModel(GenderRace genderRace, CustomizeParameter customizeParameter, CustomizeData customizeData, ParsedModelInfo modelInfo, SceneBuilder scene, List`1 bones, BoneNodeBuilder rootBone, Matrix4x4 transform) in /home/runner/work/Meddle/Meddle/Meddle/Meddle.Plugin/Models/Composer/CharacterComposer.cs:line 68
	   at Meddle.Plugin.Models.Composer.CharacterComposer.ComposeModels(ParsedModelInfo[] models, GenderRace genderRace, CustomizeParameter customizeParameter, CustomizeData customizeData, ParsedSkeleton skeleton, SceneBuilder scene, NodeBuilder root) in /home/runner/work/Meddle/Meddle/Meddle/Meddle.Plugin/Models/Composer/CharacterComposer.cs:line 319
	   at Meddle.Plugin.UI.LiveCharacterTab.<>c__DisplayClass34_2.<DrawDrawObject>b__2() in /home/runner/work/Meddle/Meddle/Meddle/Meddle.Plugin/UI/LiveCharacterTab.cs:line 281
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	   --- End of inner exception stack trace ---

**Comment by PassiveModding** [comment]
Issues should be resolved as of [v0.1.19.2](https://github.com/PassiveModding/Meddle/releases/tag/v0.1.19.2)
