### ISSUE TITLE
[BUG] Custom skeletons break full character export

### ISSUE THREAD

**Issue by dollth-ing** [PassiveModding/Meddle#20]
When trying to export a full character model through meddle, having any custom skeleton enabled will cause nothing to generate and only leave a cache folder

1. Have a custom skeleton such as ivcs, skelomae or yas enabled
2. Go to character 
3. Click export all models
4. See no models or textures are made

I expect a model and textures to be generated, with bones included

Result:
![image](https://github.com/user-attachments/assets/32593062-0c43-4372-9018-c690cde8e190)

Expected Result:
![image](https://github.com/user-attachments/assets/223231c8-9b71-48a5-909c-173fb0e6e0da)

/xllogs:
17:48:05.167 | ERR | Unobserved exception in Task.
	System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Matrix cannot be inverted. (Parameter 'jointWorldTransform'))
	 ---> System.ArgumentException: Matrix cannot be inverted. (Parameter 'jointWorldTransform')
	   at SharpGLTF.Schema2.Skin.BindJoints(Matrix4x4 meshBindTransform, Node[] joints)
	   at SharpGLTF.Schema2.Toolkit.WithSkinBinding(Node node, Matrix4x4 meshPoseTransform, Node[] joints)
	   at SharpGLTF.Scenes.SkinnedTransformer.SharpGLTF.Scenes.Schema2SceneBuilder.IOperator<SharpGLTF.Schema2.Scene>.ApplyTo(Scene dstScene, Schema2SceneBuilder context)
	   at SharpGLTF.Scenes.Schema2SceneBuilder.AddMeshes(Scene dstScene, SceneBuilder srcScene)
	   at SharpGLTF.Scenes.Schema2SceneBuilder.AddScene(Scene dstScene, SceneBuilder srcScene)
	   at SharpGLTF.Scenes.SceneBuilder.ToGltf2(IEnumerable`1 srcScenes, SceneBuilderSchema2Settings settings)
	   at SharpGLTF.Scenes.SceneBuilder.ToGltf2()
	   at Meddle.Plugin.UI.LiveCharacterTab.<>c__DisplayClass37_1.<ExportAllModels>b__1() in /home/runner/work/Meddle/Meddle/Meddle/Meddle.Plugin/UI/LiveCharacterTab.cs:line 417
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	   --- End of inner exception stack trace ---

yas: https://heliosphere.app/mod/yab
skelomae: https://www.nexusmods.com/finalfantasy14/mods/2016?tab=posts
ivcs: https://drive.google.com/drive/folders/1kZ_X7Lp38MAxbcHgsrFAAtf40CvJUXFF

**Comment by PassiveModding** [comment]
I've tested this with both ivcs and skelomae without issue. Perhaps it's related to customize+ scaling?

**Comment by jaltaer** [comment]
Just wanted to chime in that I'm having the same issue. I've tried exporting with:
- both C+ and custom skeleton (Skelomae) enabled
- C+ disabled, skeleton enabled
- C+ enabled, skeleton disabled
- both C+ and skeleton disabled

Only the last option (both C+ or skeleton disabled) gave me the expected result, having either/both of them enabled results in the same thing as OP with only the "cache" folder being exported.
